export const MODEL_ENGINE_API_URL =
  process.env.REACT_APP_MODEL_ENGINE_API_URL || window.MODEL_ENGINE_API_URL;
export const PRODUCT_SERVER_API_URL =
  process.env.REACT_APP_PRODUCT_SERVER_API_URL || window.PRODUCT_SERVER_API_URL;
