# Generated by Django 3.2.11 on 2022-01-29 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('install_ts', models.DateTimeField(auto_now_add=True)),
                ('update_ts', models.DateTimeField(auto_now=True)),
                ('created_by_id', models.IntegerField(blank=True, null=True)),
                ('updated_by_id', models.IntegerField(blank=True, null=True)),
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.TextField(choices=[('ACCESSORIES', 'ACCESSORIES'), ('CLOTHING', 'CLOTHING')], default='CLOTHING')),
                ('metadata', models.JSONField(default=dict)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'pd_product',
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name', 'type'], name='pd_product_name_5ae812_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('name', 'type')},
        ),
    ]
