# Generated by Django 3.2.11 on 2022-02-01 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_domain', '0007_alter_product_id'),
    ]

    operations = [
        migrations.RenameField(model_name='handbagdetail', old_name='metadata', new_name='meta',),
        migrations.RenameField(model_name='product', old_name='metadata', new_name='meta',),
    ]
