# Generated by Django 3.2.11 on 2022-03-01 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_domain', '0008_auto_20220201_0551'),
    ]

    operations = [
        migrations.AddField(
            model_name='handbagdetail',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
