storage:
    redis: redis://localhost:6379/0
    cache: redis://localhost:6379/0
celery:
    broker_url: redis://localhost:6379/0
database:
    name: product_design
    host: localhost
    port: 5432
handbags:
    generator:
        pickle_models: /content/product-design/src/model_engine/media/handbag/models/generator_model.pkl
        image_map_dimensions: 10
        fps: 16
        num_interps: 10
        results_size: 256
    media:
        images: /content/product-design/src/model_engine/media/handbag/images
        output_gifs: media/output_gifs/handbags/
        