storage:
    redis: redis://localhost:6379/0
    cache: redis://localhost:6379/0
celery:
    broker_url: amqp://guest:guest@localhost:5672//
database:
    name: product_design
    host: localhost
    port: 5432
    user: pd_admin
    password: password
handbags:
    generator:
        pickle_models: /content/product-design/src/model_engine/media/handbag/models/generator_model.pkl
        image_map_dimensions: 10
        fps: 16
        num_interps: 10
        results_size: 256
    media:
        images: /content/product-design/src/product_design_ui/product_design_ui/public/handbag
        output_gifs: /content/product-design/src/product_design_ui/product_design_ui/public/output
product_design:
    host: http://127.0.0.1:8000
